spring:
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SangoClothingStore}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:rootroot}
  flyway:
    enabled: true
    baseline-on-migrate: true
  mvc:
    throwExceptionIfNoHandlerFound: true


